title: Enze "Alex" Liu
subtitle: Computer Security and Privacy Researcher
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://alexliu0809.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /#/
    - text: Research
      url: /publications/
    - text: Recent News
      url: /news/
    #- text: Research
      #url: /research/
    - text: Useful links
      url: /useful_links/
    - text: Blog
      url: /blog/
#    - text: Shop
#      url : /shop/
#    - text: Contact Me
#      url : /contact/
#    - text: Styleguide
#      url: /styleguide/

recent_news:
  - date: 2022-08-01
    content: Our paper that studies the functionality and insecurity of consumer android spyware apps is accepted to PETS '23!
  - date: 2021-08-19
    content: Two papers are accepted to IMC '21! Stay tuned for the camera ready paper.
  - date: 2021-01-06
    content: Trufflehunter is awarded IETF/IRTF Applied Networking Research Prize (ANRP)! Woohoo!
  - date: 2020-10-26
    content: We've released our code for Trufflehunter.
  - date: 2020-08-11
    content: Trufflehunter is accepted to IMC 2020! Big congrats to our lead author Audrey.
  - date: 2019-09-23
    content: Joining UCSD as a first-year PhD student! I am affiliated with Sysnet and CryptoSec research groups.
  - date: 2019-09-08
    content: Arrived in San Diego! Love the sunshine here.
  - date: 2019-05-20
    content: Presenting our paper "Reasoning Analytically About Password-Cracking Software" at IEEE S&P 2019 (Oakland).
  - date: 2019-02-01
    content: After two years of work, our work on reasoning analytically about password-cracking software is finally accepted by IEEE S&P 2019 ("Oakland").
  - date: 2018-03-21
    content: Received my master's degree from UChicago! Many thanks to my family and friends who have always been supportive.
  - date: 2016-09-20
    content: Starting my master's study at The University of Chicago.

# Edit these details 

author_logo: portrait_ratio_43.jpg
author: Enze "Alex" Liu
# author_bio: 
author_email: "e7liu@eng.ucsd.edu"
author_location: La Jolla, CA
author_website_url: "https://alexliu0809.github.io"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: ucsd.png
                college_name: University of California San Diego
                college_url: https://www.ucsd.edu
                college_degree: PhD in Computer Science
                description: 2019.06 - Present
                visibility: true
              - college_logo: uchicago.png
                college_name: The University of Chicago
                college_url: https://www.uchicago.edu
                college_degree: MS in Computer Science
                description: 2016.09 - 2018.03
                visibility: true
              - college_logo: ucl.png
                college_name: University College London
                college_url: https://www.ucl.ac.uk
                college_degree: Study Abroad
                description: 2015.09 - 2016.06
                visibility: true
              - college_logo: bit.png
                college_name: Beijing Institute of Technology
                college_url: https://www.bit.edu.cn
                college_degree: BS in Software Engineering
                description: 2012.09 - 2016.06
                visibility: true

author_projects_details:
              - project_thumbnail: hc.jpeg
                project_title: Reasoning Analytically About Password-Cracking Software
                project_description: A software to reason analytically and efficiently about transformation-based password cracking in software tools like John the Ripper (JtR) and Hashcat (HC).
                project_url: https://github.com/UChicagoSUPERgroup/analytic-password-cracking
                visibility: true

              # - project_thumbnail: programmingebooks.png
              #   project_title: Programming Ebooks
              #   project_description: A Platform to easily find and read programming books
              #   project_url: https://programmingebooks.com
              #   visibility: false

author_pubs_details:
              - title: "No Privacy Among Spies: Assessing the Functionality and Insecurity of Consumer Android Spyware Apps"
                author_list:
                  - name: Enze Liu
                  - name: Gautam Akiwate
                  - name: Mattijs Jonker
                  - name: Ariana Mirian
                  - name: Grant Ho
                  - name: Geoffrey M. Voelker
                  - name: Stefan Savage
                venue: the 8th IEEE European Symposium on Security and Privacy (EuroS&P '23)
                venue_short: IEEE EuroS&P
                year: 2023


              - title: "No Privacy Among Spies: Assessing the Functionality and Insecurity of Consumer Android Spyware Apps"
                author_list:
                  - name: Enze Liu
                  - name: Sumanth Rao
                  - name: Sam Havron
                  - name: Grant Ho
                  - name: Stefan Savage
                  - name: Geoffrey M. Voelker
                  - name: Damon McCoy
                venue: the 23rd Privacy Enhancing Technologies Symposium (PETS '23)
                venue_short: PETS
                year: 2023
                links:
                  - type: Paper
                    url: https://petsymposium.org/popets/2023/popets-2023-0013.pdf

              - title: "Who's Got Your Mail? Characterizing Mail Service Provider Usage"
                author_list:
                  - name: Enze Liu
                  - name: Gautam Akiwate
                  - name: Mattijs Jonker
                  - name: Ariana Mirian
                  - name: Stefan Savage
                  - name: Geoffrey M. Voelker
                venue: the ACM Internet Measurement Conference 2021 (IMC '21)
                venue_short: ACM IMC
                year: 2021
                links:
                  - type: Paper
                    url: https://www.sysnet.ucsd.edu/~voelker/pubs/mx-imc21.pdf
                  - type: Code
                    url: https://github.com/ucsdsysnet/mx_inference
                  - type: Slides
                    url: https://github.com/alexliu0809/alexliu0809.github.io/blob/876c5a0f380db6d2d6d8bf519589a61e508c1889/assets/files/Paper57-Liu.pdf?raw=true
                  - type: Talk
                    url: https://www.youtube.com/watch?v=EeujjO_OJdo&list=PL4iXY1PzLoNpXfQNpwuDDF155sZhGa4iX&index=45


              - title: "Home is Where the Hijacking is: Understanding DNS Interception by Residential Routers"
                author_list:
                  - name: Audrey Randall
                  - name: Enze Liu
                  - name: Ramakrishna Padmanabhan
                  - name: Gautam Akiwate
                  - name: Geoffrey M. Voelker
                  - name: Stefan Savage
                  - name: Aaron Schulman
                venue: the ACM Internet Measurement Conference 2021 (IMC '21)
                venue_short: ACM IMC
                year: 2021
                links:
                  - type: Paper
                    url: https://www.sysnet.ucsd.edu/~voelker/pubs/homejack-imc21.pdf



              - title: "Trufflehunter: Cache Sniffing Rare Domains at Large Public DNS Resolvers"
                author_list:
                  - name: Audrey Randall
                  - name: Enze Liu
                  - name: Gautam Akiwate
                  - name: Ramakrishna Padmanabhan
                  - name: Geoffrey M. Voelker
                  - name: Stefan Savage
                  - name: Aaron Schulman
                venue: the ACM Internet Measurement Conference 2020 (IMC '20)
                venue_short: ACM IMC
                year: 2020
                links:
                  - type: Paper
                    url: https://cseweb.ucsd.edu/~schulman/docs/imc20-trufflehunter.pdf
                  - type: Code
                    url: https://github.com/ucsdsysnet/trufflehunter
                award: IRTF Applied Networking Research Prize

              - title: Reasoning Analytically About Password-Cracking Software
                author_list:
                  - name: Enze Liu
                  - name: Amanda Nakanishi
                  - name: Maximilian Golla
                  - name: David Cash
                  - name: Blase Ur
                venue: the 40th IEEE Symposium on Security and Privacy (S&P '19)
                venue_short: IEEE S&P
                year: 2019
                links:
                  - type: Paper
                    url: https://www.blaseur.com/papers/sp19-pwcracking.pdf
                  - type: Code
                    url: https://github.com/UChicagoSUPERgroup/analytic-password-cracking/
                  - type: Slides
                    url: https://www.ieee-security.org/TC/SP2019/SP19-Slides-pdfs/Enze_Alex_Liu_-_06-Reasoning_Analytically_About_Password-Cracking_Software.pdf
                  - type: Talk
                    url: https://youtu.be/kSfmTV0GTIM



restaurants:
    - location: San Diego
      restaurants:
          - name: Creme De La Crepe (French)
            dishes:
              - dish: Country paté plate
          - name: Spitfire Tacos (Mexican)
            dishes:
              - dish: Tacos
              - dish: Churros
          - name: The Taco Stand (Mexican)
            dishes:
              - dish: Burrito and Salsa
          - name: Menya Ultra (Japenese)
            dishes:
              - dish: Ramen
          - name: HiroNori Craft Ramen (Japenese)
            dishes:
              - dish: Ramen
          - name: Costa Brava (Spanish)
            dishes:
              - dish: Zarzuela de Marisco
          - name: Caroline's Seaside Cafe (American)
            dishes :
              - dish: The sea view! (also discounts for UCSD students)
          - name: Kaiserhof Restaurant (German)
            dishes:
              - dish: German sausage
          - name: Taste of Denmark (Danish)
            dishes:
              - dish: Open sandwich!
          - name: Paradise Biryani (Indian)
            dishes:
              - dish: Biryani
          - name: Piacere Mio (Italian)
            dishes:
              - dish: TAGLIERINI NERI AI FRUTTI DI MARE (Squid ink pasta with seafood)
              - dish: Choose your own pasta!
          - name: Kroran Uyghur Cuisine (Uyghur)
            dishes:
              - dish: Hand Pulled noodle
              - dish: Naan (a kind of roasted bread)
          - name: Havana Grill (Cuban)
            dishes:
              - dish: Fricasé de Pollo
              - dish: Empanada
              - dish: El Cubano
              - dish: Rabo Encendido
          - name: Soup Du Jour (Chinese)
            dishes:
              - dish: Various soups
              - dish: Chinese doughnut stick 
          - name: Alforon (Mediterranean)
            dishes:
              - dish: Phoenician Pie
              - dish: Ouzi Lamb Special
          - name: Mitch's Seafood (Seafood)
            dishes:
              - dish: Fresh fish tacos
          - name: Oscar's Mexican Seafood (Mexican)
            dishes:
              - dish: Seafood tacos
          - name: Pho Point Loma & Grill (Vietnamese)
            dishes:
              - dish: Pho
          - name: Supannee House of Thai (Thai)
            dishes:
              - dish: Boba tea
              - dish: Duck
          - name: Pomegranate (Georgian)
          - name: Romeo & Julieta Wine Cafe (Polish)
          - name: The Red Door (Italian / Fine dining)
            dishes:
              - dish: Beef wellington
          - name: Trust (New American Brunch)
            dishes:
              - dish: Ultimate sticky bun
              - dish: Smoked pork shoulder hash
          - name: Abay Ethiopian market and restaurant (Ethiopian)
            dishes:
              - dish: Beef stew
              - dish: Meat combination
          - name: Awash Ethiopian Restaurant (Ethiopian)
          - name: Plumeria Vegetarian Restaurant (Vegetarian)
            dishes:
              - dish: Vegan duck
          - name: The Purple Mint (Vegetarian)
            dishes:
              - dish: Peking "Duck" Lettuce Wraps
              - dish: Sizzling "Steak Filet Mignon"
 

    - location: Chicago
      restaurants:
          - name: Laschet's Inn (German)
            dishes:
              - dish: Beers!
          - name: Kizuki Ramen & Izakaya (Japenese)
            dishes:
              - dish: Ramen
          - name: Margeaux Brasserie (French)
            dishes:
              - dish: Duck wings À L’ORANGE
    - location: San Francisco
      restaurants:
        - name: Surisan (Korean)
          dishes:
            - dish: Brunch
fine_dining:
    - year: 2017
      name: GreenRiver
      location: Chicago, IL, USA.
    - year: 2019
      name: Alinea
      location: Chicago, IL, USA. Huge thanks to Peter Chen!
    - year: 2019
      name: Cafe China
      location: New York City, NY, USA.
    - year: 2020
      name: Addison
      location: San Diego, CA, USA.
    - year: 2021
      name: Sepia
      location: Chicago, IL, USA.
    - year: 2021
      name: Jeune et Jolie
      location: Carlsbad, CA, USA.
    - year: 2022
      name: Sushi Tadokoro
      location: San Diego, CA, USA.
    - year: 2022
      name: Jeune et Jolie
      location: Carlsbad, CA, USA.


# social links
github_username:  alexliu0809
linkedin_username: alex-enze-liu-809859125
twitter_username: alexliu1
google_scholar_id: ACUFMCoAAAAJ
#facebook_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments using disqus
#disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
# wakatime_username: alexliu0809

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: true
show_author_projects_details: false

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/